CREATE DATABASE GESTAO_BIBLIOTECAS;
GO

USE GESTAO_BIBLIOTECAS;
GO

CREATE TABLE [dbo].[TAUTORES]
(
	[COD_TAUTORES]		INT IDENTITY (1,1) NOT NULL,
	[NOME]				NVARCHAR (100) NOT NULL,
	[ATIVO]				BIT NOT NULL DEFAULT 1,

	PRIMARY KEY CLUSTERED ([COD_TAUTORES] ASC),
	CONSTRAINT [UK_TAUTORES] UNIQUE NONCLUSTERED ([NOME] ASC),
);
GO

CREATE TABLE [dbo].[TGENEROS]
(
	[COD_TGENEROS]		INT IDENTITY (1,1) NOT NULL,
	[NOME]				NVARCHAR (100) NOT NULL,
	[ATIVO]				BIT NOT NULL DEFAULT 1,

	PRIMARY KEY CLUSTERED ([COD_TGENEROS] ASC),
	CONSTRAINT [UK_TGENEROS] UNIQUE NONCLUSTERED ([NOME] ASC),
);
GO

CREATE TABLE dbo.TLIVROS
(
    COD_TLIVROS			INT IDENTITY(1,1) NOT NULL,
    NOME				NVARCHAR(100) NOT NULL,
    COD_TAUTORES		INT NOT NULL,
    COD_TGENEROS		INT NOT NULL,
    ATIVO				BIT NOT NULL DEFAULT 1,

	PRIMARY KEY CLUSTERED ([COD_TLIVROS] ASC),
    CONSTRAINT UK_TLIVROS UNIQUE(NOME),
    CONSTRAINT FK_LIVROS_AUTORES FOREIGN KEY (COD_TAUTORES) REFERENCES dbo.TAUTORES(COD_TAUTORES),
    CONSTRAINT FK_LIVROS_GENEROS FOREIGN KEY (COD_TGENEROS) REFERENCES dbo.TGENEROS(COD_TGENEROS)
);
GO

USE GESTAO_BIBLIOTECAS;
GO

-- INSERÇÃO DOS AUTORES
INSERT INTO dbo.TAUTORES (NOME, ATIVO) VALUES
('Machado de Assis', 1),
('Clarice Lispector', 1),
('J.K. Rowling', 1);

-- INSERÇÃO DOS GENEROS
INSERT INTO dbo.TGENEROS (NOME, ATIVO) VALUES
('Romance', 1),
('Ficção', 1),
('Biografia', 1);

-- INSERÇÃO DOS LIVROS
INSERT INTO dbo.TLIVROS (NOME, COD_TAUTORES, COD_TGENEROS, ATIVO) VALUES
('Dom Casmurro', 1, 1, 1),
('A Hora da Estrela', 2, 1, 1),
('Harry Potter e a Pedra Filosofal', 3, 3, 1),
('Harry Potter e a Camara Seecreta', 3, 3, 1),
('Harry Potter e o Cálice de Fogo', 3, 3, 1);


SELECT * FROM TAUTORES AS AUT
SELECT * FROM TGENEROS AS GEN
SELECT * FROM TLIVROS AS LIV